[package]
name = "rust-chip8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
sfml = "0.21.0"

[[bin]]
name = "rust-chip8"
path = "src/main.rs"
